language: node_js
node_js:
  - 12

notifications:
  email: false

script:
  - npm run validate

after_script:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        script:
          - npx semantic-release
